name: getCustomerPayments
query: |-
    query getCustomerPayments{
      customers {
        id
        email
        payments {
          customer_id
          amount
          billing_details
        }
      }
    }
vars: '{}'
